# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-16 21:22
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diva', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
